log_dir: ???
effect_time_window: 10
display_results: true
module_setting:
  perception:
    perc_score_threshold: 0.5
  prediction:
    prediction_window: 10
    pred_score_threshold: 0.1
  planning:
    planning_toleration_future_step: 5
    planning_toleration: 2